search {
  index = cortex
  uri = "http://thehive-es:9200"
}

cache.job = 10 minutes

play.filters.enabled = [
  org.thp.cortex.services.StreamFilter,
  org.elastic4play.services.TempFilter,
  org.thp.cortex.services.AccessLogFilter
]

auth {
  provider = [local, oidc]
  sso {
    autocreate = true
    autoupdate = false
    mapper = "simple"
    attributes {
      login = "email"
      name = "name"
    }
    defaultRoles = ["superadmin", "orgAdmin", "read", "analyze"]
    defaultOrganization = "cortex"
    oidc {
      clientId = "cortex"
      clientSecret = ${?CORTEX_OIDC_CLIENT_SECRET}
      url = "http://10.10.50.70/realms/master"
      redirectUrl = "http://10.10.50.24/api/ssoLogin"
      scope = ["openid", "profile", "email"]
    }
  }
}
